stages:
  - deploy

deploy:
  stage: deploy
  image: node:16
  script:
    - npm install -g caprover
    - caprover deploy --appName $CAPROVER_APP --appToken $CAPROVER_APP_TOKEN --captainURL $CAPROVER_URL
  only:
    - main