services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel
    container_name: laravel-app
    restart: unless-stopped
    working_dir: /var/www
    ports:
      - "3000:80"
    volumes:
      - storage:/var/www/storage
      - cache:/var/www/bootstrap/cache
    networks:
      - laravel
    depends_on:
      - db
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost/health || exit 0"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 30s
    labels:
      - "traefik.http.middlewares.upload-limit.buffering.maxRequestBodyBytes=67108864"
      - "traefik.http.routers.myapp.middlewares=upload-limit@docker"

  scheduler:
    image: laravel
    container_name: laravel-scheduler
    restart: unless-stopped
    command: ["php", "/var/www/artisan", "schedule:work"]
    volumes:
      - storage:/var/www/storage
      - cache:/var/www/bootstrap/cache
    networks:
      - laravel
    depends_on:
      - app

  # Uncomment the following block if you're using SSR
  # ssr:
  #   image: laravel
  #   container_name: laravel-ssr
  #   restart: unless-stopped
  #   command: ["php", "/var/www/artisan", "inertia:start-ssr"]
  #   volumes:
  #     - storage:/var/www/storage
  #     - cache:/var/www/bootstrap/cache
  #   networks:
  #     - laravel
  #   depends_on:
  #     - app

  db:
    image: mariadb:11.4
    container_name: laravel-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel
    healthcheck:
      test:
        - CMD
        - mariadb-admin
        - ping
        - "-h127.0.0.1"
        - "-uroot"
        - "-p${DB_PASSWORD}"
      interval: 5s
      timeout: 20s
      retries: 10

networks:
  laravel:
    driver: bridge

volumes:
  storage:
    driver: local
  cache:
    driver: local
  dbdata:
    driver: local