name: Deploy to CapRover

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Deploy to CapRover
        uses: caprover/deploy-from-github@v1.0.1
        with:
          server: 'https://captain.scenic-routes.live'
          app: 'scenic-routes'
          token: ${{ secrets.CAPROVER_TOKEN }}