name: Deploy to CapRover

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install CapRover CLI
        run: npm install -g caprover
      
      - name: Deploy to CapRover
        run: caprover deploy --appName scenic-routes --appToken ${{ secrets.CAPROVER_APP_TOKEN }} --captainURL https://captain.scenic-routes.live